---
title: "Preprocessing"
output: html_document
---

## Preprocessing analysis

```{r}
#libraries and data upload 
library(ggplot2)
library(urca)
library(tseries)
data <- read.csv("data/UMCSENT.csv")

```

```{r}
#Raw data analysis
str(data) # observation_date chr; UMCSENT num
data$observation_date <- as.Date(data$observation_date, format = "%Y-%m-%d") # observation_date conversion to Date
str(data)

sum(is.na(data$UMCSENT)) # check missing values
mean(is.na(data$UMCSENT)) # percentage of missing values

nrow(data)
range(data$observation_date)

ggplot(data, aes(x = observation_date, y = UMCSENT)) +
  geom_line() +
  labs(title = 'Consumer Sentiment Index')

```

```{r}
#Data preparation and summaries
# data from 1978
data_filtered <- subset(data, observation_date >= "1978-01-01")
nrow(data_filtered)
range(data_filtered$observation_date)
ggplot(data_filtered, aes(x = observation_date, y = UMCSENT)) +
  geom_line() +
  labs(title = 'Consumer Sentiment Index')

# statistics
summary(data_filtered$UMCSENT)

# check for outliers
hist(data_filtered$UMCSENT, breaks = 20)
boxplot(data_filtered$UMCSENT)

```

```{r}
# STATIONARITY TEST ------------------------------------------------------------------
# ADF -> stationary
summary(ur.df(data_filtered$UMCSENT, type = "drift"))
# KPSS -> non-stationary
kpss.test(data_filtered$UMCSENT)

```

```{r}
# AUTOCORRELATION --------------------------------------------------------------------
acf(data_filtered$UMCSENT)
pacf(data_filtered$UMCSENT)

```
```{r}
#first difference
diff_1 <- diff(data_filtered$UMCSENT)
```

```{r}
# CORRELATION TEST
#Barletts' bands
bartlett.test(data_filtered$UMCSENT ~ as.factor(cut(seq_along(data_filtered$UMCSENT), 10))) # suggests log-transformation
#Box-Pierce
Box.test(data_filtered$UMCSENT, lag = 10, type = "Box-Pierce") # high autocorrelation
Box.test(diff_1, lag = 10, type = "Box-Pierce")
#Ljung-Box
Box.test(data_filtered$UMCSENT, lag = 10, type = "Ljung-Box") # high autocorrelation

```

```{r}
#data filtered
data_filtered$log_UMCSENT <- log(data_filtered$UMCSENT)

diff_log <- diff(data_filtered$log_UMCSENT)

alligned_diff_log <- c(NA, diff_log)

data_filtered$diff_log_UMCSENT <- alligned_diff_log

head(data_filtered)
```

```{r}
#acf and pacf of filtered data
acf(na.omit(data_filtered$diff_log_UMCSENT))
pacf(na.omit(data_filtered$diff_log_UMCSENT))
```
