---
title: "alternative_model_2"
output: html_document
date: "2025-11-19"
---

# VAR Model

## 1. Data Import

```{r}
data_unrate <- read.csv("data/UNRATE.csv") 

data_unrate$observation_date <- as.Date(data_unrate$observation_date, format = "%Y-%m-%d")

# Align Dates
data_unrate_filtered <- subset(data_unrate, observation_date >= "1978-01-01")

cat("Righe UMCSENT:", nrow(data_filtered), "\n")
cat("Righe UNRATE:", nrow(data_unrate_filtered), "\n")

# Merge based on date
data_multivariate <- merge(data_filtered, data_unrate_filtered, by = "observation_date")

str(data_multivariate)

# Comparison plot
ggplot(data_multivariate, aes(x = observation_date)) +
  geom_line(aes(y = scale(UMCSENT), color = "Sentiment (Scaled)")) +
  geom_line(aes(y = scale(UNRATE), color = "Unemployment (Scaled)")) +
  labs(title = "Sentiment vs Unemployment",
       x = "Year",
       y = "Scaled Values",
       color = "") +
  theme_minimal()
```

## 2. Stationarity Test on Unemployment Rate

```{r}

# Original Series

# Plot
ggplot(data_multivariate, aes(x = observation_date, y = UNRATE)) +
  geom_line() +
  labs(title = 'Unemployment Rate (Originale)')

# Stationarity Test
cat("--- Test on UNRATE (Level) ---\n")

# ADF (H0: Non-stationary)
summary(ur.df(data_multivariate$UNRATE, type = "drift"))

# KPSS (H0: Stationary)
kpss.test(data_multivariate$UNRATE)

```

```{r}

# First Difference
diff_unrate <- diff(data_multivariate$UNRATE)

data_multivariate$diff_UNRATE <- c(NA, diff_unrate)

# Plot
ggplot(data_multivariate, aes(x = observation_date, y = diff_UNRATE)) +
  geom_line() +
  labs(title = 'First Difference of Unemployment Rate')

# Stationarity Test on Differenced Data 
cat("\n--- Test on diff_UNRATE (Differenced) ---\n")

# ADF 
summary(ur.df(na.omit(data_multivariate$diff_UNRATE), type = "drift"))

# KPSS
kpss.test(na.omit(data_multivariate$diff_UNRATE))
```

### 3. ACF and PACF on Differenced Data

```{r}
# ACF and PACF on differenced data
par(mfrow = c(1, 2)) 

# ACF
acf(na.omit(data_multivariate$diff_UNRATE), 
    main = "ACF - Diff. Unemployment", 
    lag.max = 36)

# PACF
pacf(na.omit(data_multivariate$diff_UNRATE), 
     main = "PACF - Diff. Unemployment", 
     lag.max = 36)

par(mfrow = c(1, 1))
```

## 3. Data Split - Training and Test Set

```{r}
library(vars)
library(ggplot2)

var_cols <- c("diff_log_UMCSENT", "diff_UNRATE")
var_data <- na.omit(data_multivariate[, var_cols])

# Train/Test - 80%/20%
n_obs <- nrow(var_data)
split_point <- floor(0.80 * n_obs)

train_var <- var_data[1:split_point, ]
test_var <- var_data[(split_point + 1):n_obs, ]

cat("Training Set:", nrow(train_var), "observations\n")
cat("Test Set:    ", nrow(test_var), "observations\n")


```

## 4. AIC/BIC Comparison

```{r}

# Lag selection on training set
lag_selection_train <- VARselect(train_var, lag.max = 12, type = "const")

# Suggestions
print(lag_selection_train$selection)

# Plot AIC vs. BIC

# criteria_df
criteria_df <- data.frame(
  Lag = 1:12, 
  t(lag_selection_train$criteria)
)

df_plot <- data.frame(
  Lag = rep(1:12, 2),
  Value = c(criteria_df$AIC.n, criteria_df$SC.n),
  Metric = c(rep("AIC (Prediction)", 12), rep("BIC (Simplicity)", 12))
)

# Plot
ggplot(df_plot, aes(x = Lag, y = Value, color = Metric, group = Metric)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_continuous(breaks = 1:12) +
  labs(title = "Optimal lag",
       y = "Information Criteria",
       x = "Lag Order (p)") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

## 5. VAR Model

```{r}

# Model Estimation

# 1. optimal p selection
optimal_p <- 12 #lag_selection_train$selection["AIC(n)"]
cat("The model is estimated with p =", optimal_p, "lag.\n")

# 2. model estimation
model_var <- VAR(train_var, p = optimal_p, type = "const")

# 3. results
summary(model_var)

# 4. stability check (roots)
roots_var <- roots(model_var)
cat("\n--- Stability Check ---\n")
if(all(roots_var < 1)){
  cat("Stable (all roots < 1).\n")
} else {
  cat("ATTENTION: unstable. \n")
}
print(roots_var)
```

## 6. Residual Diagnostics

```{r}
# Residuals Diagnostics

serial_t <- serial.test(model_var, lags.pt = 16, type = "PT.asymptotic")
print(serial_t)

# ACF Residuals
plot(serial_t, names = "diff_log_UMCSENT") 

# ARCH Test
arch_t <- arch.test(model_var, lags.multi = 12)
print(arch_t)


# Normality Test
norm_t <- normality.test(model_var, multivariate.only = FALSE)
print(norm_t$jb.uni)
```

## 7. Granger-Causality Check

```{r}

# Granger Causality Test

# Test A: Does (diff_UNRATE) cause Sentiment?
# H0: unemployment does not cause-Granger Sentiment.
# H1: unemployment cause-Granger Sentiment.
granger_from_unrate <- causality(model_var, cause = "diff_UNRATE")

cat("does UNRATE help predict UMCSENT? ---\n")
print(granger_from_unrate$Granger)

# Test B: (diff_log_UMCSENT) cause Unemployment?
granger_from_sentiment <- causality(model_var, cause = "diff_log_UMCSENT")

cat("does UMCSENT help predict UNRATE? ---\n")
print(granger_from_sentiment$Granger)
```

## 8. Forecast

```{r}

window_size <- nrow(train_var) 
total_obs <- nrow(var_data)
test_start_index <- window_size + 1

forecasts_diff <- numeric()
actuals_diff <- var_data$diff_log_UMCSENT[test_start_index:total_obs]

cat("Rolling Window Forecasting...\n")
cat("Training Window:", window_size, "months.\n")
cat("Forecasts to generate:", length(actuals_diff), "\n")

for (i in 0:(length(actuals_diff) - 1)) {
  
  current_train_idx <- (1 + i):(window_size + i)
  current_data <- var_data[current_train_idx, ]
  
  fit_rolling <- tryCatch({
    VAR(current_data, p = optimal_p, type = "const")
  }, error = function(e) return(NULL))
  
  if (!is.null(fit_rolling)) {
    pred <- predict(fit_rolling, n.ahead = 1)
    fcst_value <- pred$fcst$diff_log_UMCSENT[1, "fcst"]
    forecasts_diff <- c(forecasts_diff, fcst_value)
  } else {
    forecasts_diff <- c(forecasts_diff, NA)
  }
}

cat("Rolling Forecast completato.\n")

test_indices_original <- (nrow(var_data) - length(actuals_diff) + 1):nrow(var_data)


actual_log_levels <- data_multivariate$log_UMCSENT[test_indices_original + 1]
last_train_log_level <- data_multivariate$log_UMCSENT[test_indices_original[1]]

forecast_log_levels <- numeric(length(forecasts_diff))
prev_value <- last_train_log_level

actual_logs_shifted <- data_multivariate$log_UMCSENT[test_indices_original] # t-1
forecast_log_levels <- actual_logs_shifted + forecasts_diff

df_results <- data.frame(
  Date = data_multivariate$observation_date[test_indices_original + 1],
  Actual_Log = actual_log_levels,
  Forecast_Log_VAR = forecast_log_levels,
  Diff_Pred = forecasts_diff
)

head(df_results)
```

### Plot

```{r}

# Actual vs Forecast
ggplot(df_results, aes(x = Date)) +
  geom_line(aes(y = Actual_Log, color = "Actual Data"), size = 1) +
  geom_line(aes(y = Forecast_Log_VAR, color = "VAR Forecast (Rolling)"), size = 0.8, linetype = "dashed") +
  labs(title = "VAR vs Actual data (in logs)",
       subtitle = paste("Rolling Window 1-step ahead | RMSE:", round(rmse_var, 4)),
       y = "Log(Consumer Sentiment)",
       color = "Legenda") +
  theme_minimal() +
  scale_color_manual(values = c("Dati Reali" = "black", "VAR Forecast (Rolling)" = "red"))
```

### RMSE

```{r}
# 10. Valutazione Performance

# Calcolo Errori
rmse_var <- sqrt(mean((df_results$Actual_Log - df_results$Forecast_Log_VAR)^2, na.rm = TRUE))
mae_var <- mean(abs(df_results$Actual_Log - df_results$Forecast_Log_VAR), na.rm = TRUE)

cat("--- Performance Model VAR (Rolling Window) ---\n")
cat("RMSE (Log Scale):", round(rmse_var, 4), "\n")
cat("MAE  (Log Scale):", round(mae_var, 4), "\n")


```
